version: "3.7"

services:
  backend:
    build:
      context: .
      dockerfile: docker/backend.Dockerfile
    container_name: backend
    restart: always
    #  mount the volumes so we can change code and hot reload
    volumes:
      - .:/app
    ports:
      - 8000:8000

  frontend:
    build:
      context: .
      dockerfile: docker/frontend.Dockerfile
    container_name: frontend
    volumes:
      - .:/app
    ports:
      - 3000:3000
    user: ${CURRENT_UID}
